#####################################################################################
#                                                                                   #
#                              General Configurations                               #
#                                                                                   #
#####################################################################################

# an elaborate tutorial and setup guide can be found on our wiki:
# https://github.com/TavernCraft-Devs/SurvivalTop/wiki

# the plugin also comes with placeholder api support that can be found here:
# https://github.com/TavernCraft-Devs/SurvivalTop/wiki/Tutorial#placeholderapi-support

# language file to use (feel free to add your own lang file within the lang folder of the plugin and put the name here)
lang-file: 'en.yml'

# if true, will provide a detailed gui for viewing entity stats
# if realtime stats are used as well, then this includes individual item/block breakdowns
# if false, will provide only basic entity stats in chat without detailed breakdown
# for servers very worried about lags, consider setting this to false
use-gui-stats: false

# if true, will provide realtime values when the stats command is executed
# realtime calculations take a longer time depending on the claim size, spawner count etc
# if false, will provide the cached value from the previous calculation
# cached values provide near instant results (very much faster) but are not the latest
# cache duration specifies in seconds how long cached data is stored
# cache duration is ignored if realtime stats is used
# note that if cached values cannot be found, the plugin defaults to getting real time stats
use-realtime-stats: false
cache-duration: 1800

#####################################################################################
#                                                                                   #
#                    Filter Options (not applicable to groups!)                     #
#                                                                                   #
#####################################################################################

# the below options only apply if you have enable-group set to false (i.e. entity = player)
# these options are also mostly applicable to very old or large servers that find leaderboard
# updates taking a very long time
# for a full and clearer explanation on how to use this, please take a look at our wiki:
# https://github.com/TavernCraft-Devs/SurvivalTop/wiki/Tutorial#filter-options
filter-last-join: false
filter-player-time: 2592000

#####################################################################################
#                                                                                   #
#                               Group Configurations                                #
#                                                                                   #
#####################################################################################

# by default, the term entity in this plugin refers to players
# however, if enable-groups is set to true, then entity refers to a group (e.g. factions, kingdom)
# this option should only be set to true for users who wish to show group-based leaderboards
# make sure a valid group-type is set below and the relevant plugin is installed
# otherwise, if enabled without a valid group-type, plugin will still disable group
enable-group: false

# the group-type option only works if enable-groups is set to true with the relevant plugin installed
# options supported for group-type can be found on our wiki:
# https://github.com/TavernCraft-Devs/SurvivalTop/wiki/Tutorial#group-options
group-type: FactionsUuid

#####################################################################################
#                                                                                   #
#                               Balance Integration                                 #
#                                                                                   #
#####################################################################################

# if true, will include player /balance in calculating wealth (requires vault)
include-bal: false

#####################################################################################
#                                                                                   #
#                            Land Claim Plugin Integration                          #
#                                                                                   #
#####################################################################################

# if true, will include blocks in land for calculating wealth (requires a land claim plugin)
include-land: false

# if you are intending to include land, make sure a valid land type is set below
# options supported for land-type can be found on our wiki:
# https://github.com/TavernCraft-Devs/SurvivalTop/wiki/Tutorial#land-options
land-type: GriefPrevention

# if true, spawners will be included as part of land wealth in calculations
# also requires include-land to be true!
# note that checks for spawners are more expensive and you should consider disabling this if updates take too long
include-spawners: false

# if true, containers (chest, trapped_chest, hopper, dropper, furnace) will be included as part of land wealth in calculations
# also requires include-land to be true!
# note that checks for containers are the most expensive and you should consider disabling this if updates take too long
include-containers: false

# list of containers that will be checked
# this list is ignored if include-containers is false
container-type:
  - CHEST
  - TRAPPED_CHEST

# the following 2 options are recommended to be left as default to use the heights provided by
# the land plugin
# if you wish to adjust this, kindly refer to a more detailed explanation on the wiki:
# https://github.com/TavernCraft-Devs/SurvivalTop/wiki/Tutorial#land-options
max-land-height: default
min-land-height: default

#####################################################################################
#                                                                                   #
#                              Inventory Integration                                #
#                                                                                   #
#####################################################################################

# if true, will include player inventory in calculating wealth (currently only works for online players)
include-inventory: false

#####################################################################################
#                                                                                   #
#                             Leaderboard Configuration                             #
#                                                                                   #
#####################################################################################

# interval (in seconds) between updating the leaderboard (set to -1 to disable)
# not recommended updating too frequently, especially if you have a large player-base
# plugin reloads will restart/update this interval count from the point of reload
update-interval: 3600

# if true, will first update leaderboard on server start
# if false, will first update leaderboard upon reaching the specified interval
update-on-start: false

# minimum wealth (inclusive) required to be included on the leaderboard - 0 will disallow negative wealth on leaderboard
minimum-wealth: 0

#####################################################################################
#                                                                                   #
#                               Storage Configurations                              #
#                                                                                   #
#####################################################################################

# whether to write updated entity data to file/mysql or not at all
# options here include: MySQL, YAML and None
# note that information storage is not required for this plugin since the results of updates are stored in cache
# as of the latest version of this plugin, the storage only serves a purpose if you have your own means to make use of this information
# it is thus recommended setting this to None if you have a large player-base, lag issues or have no use for storing the information
storage-type: None

# mysql connection details (ignore if not using)
host: 127.0.0.1
port: 3306
user: survtop
password: password
database-name: survtop
table-name: survtop

#####################################################################################
#                                                                                   #
#                             Miscellaneous Configurations                          #
#                                                                                   #
#####################################################################################

# this section contains plugin-specific configurations that should be ignored if not used

# towny advanced users should make sure this block size is the same as in the towny advanced config
town-block-size: 16

